/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mark_3.testes;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFrame;

/**
 *
 * @author Gustavo
 */
public class MainPanel extends javax.swing.JPanel {
    JFrame frame;
    Image staff = null;
    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        this.setOpaque(true); ///ajeitar
        this.setBackground(Color.red);        
        initComponents();
        frame = new JFrame();
        frame.setSize(200, 200);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setContentPane(this);
        frame.setVisible(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public static void main(String[] args) {
        MainPanel panel = new MainPanel();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    @Override
    public void paintComponent(Graphics g)
    {
        if (staff == null)
        {
            staff = getImage("C:\\Users\\Gustavo\\Desktop\\music-staff-hi.png");
        }
        int deltapos = 12;
        int initpos = 117;
        Graphics2D g2 = (Graphics2D)g;
        g2.drawImage(staff, 30, 30, staff.getWidth(this), staff.getHeight(this), this);
        Image wholeNote = getImage("C:\\Users\\Gustavo\\Desktop\\whole-note.png");
        g2.drawImage(wholeNote, (100+(40*0)), (initpos-(deltapos*0)), 40, 40, this);
        g2.drawImage(wholeNote, (100+(40*1)), (initpos-(deltapos*1)), 40, 40, this);
        g2.drawImage(wholeNote, (100+(40*2)), (initpos-(deltapos*2)), 40, 40, this);
        g2.drawImage(wholeNote, (100+(40*3)), (initpos-(deltapos*3)), 40, 40, this);
        g2.drawImage(wholeNote, (100+(40*4)), (initpos-(deltapos*4)), 40, 40, this);
        g2.drawImage(wholeNote, (100+(40*5)), (initpos-(deltapos*5)), 40, 40, this);
        g2.drawImage(wholeNote, (100+(40*6)), (initpos-(deltapos*6)), 40, 40, this);
    }
    
    public Image getImage(String path)
    {
        Image tempImage = null;
        try 
        {
            tempImage = ImageIO.read(new File(path));
        } catch (Exception e)
        {
            System.out.println("Erro");
        }
        return tempImage;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
